### PR TITLE
WIP: use release api object

### LINKED ISSUE #1: Use native GitLab releases
GitLab 11.7 includes native support for [releases](https://about.gitlab.com/2019/01/22/gitlab-11-7-released/#publish-releases-for-your-projects).  The current code should be updated to use the new native releases instead of using the old tag metadata implementation.

### LINKED ISSUE #3: Get tests working
This repo was forked from the GitHub resource, so the tests need to be updated for GitLab.  This should probably go along with #1 as the resource will change quite a bit.

### PR DESCRIPTION
**Pull request by psycofdj**
Hello,

This PR uses gitlab's `release` api object instead of relying on tags. It also use releases `links` instead of parsing release's description.  

It is tagged `WIP` until I can finished tests in my staging environments. Docker image is available in `psycofdj/gitlab-release-resource:v2.0.0-rc4`

Q: Since there is not commit since 2018, are you still interested in maintaining this resource ? or should I consider forking it on my organization namespace ? 

Thanks for your work

Details:

* fixes #3 and fixes #1 
* bump module dependencies
* `out` command
  * handles `body` parameter
  * upload in project and create `Release.Assets.Links` for each file
  * add `name` metadata
* `in` command
  * download assets according to `Release.Assets.Links` instead of parsing `body` value
  * handles source download with format switch
  * add `name` metadata

### CODE REVIEW

**Comment by psycofdj** [comment]
Gitlab makes impossible de download release's assets using `private-token`, which makes the move totally useless.
see [gitlab issue](https://gitlab.com/gitlab-org/gitlab/-/issues/28978).

I'm hoping for a fix a near future, gitlab's team seems to work on the problem.

**Comment by edtan** [comment]
Thanks for looking into this!  It's too bad that we can't download Gitlab release assets.

Unfortunately, I don't have time to actively maintain this resource anymore.  Once Gitlab has added the download support, if you are still planning on working on the resource, feel free to fork it to your organization namespace, and I'll be happy to add a note to the README pointing to your fork and archive this repo.

**Comment by psycofdj** [comment]
In the end, I'm using my forked resource in production despite the lake of gitlab's support of download. I only use `get` on releases referencing external assets and uploads works fine.

Since your repository was forked from [concourse/github-release-resource](https://github.com/concourse/github-release-resource), my fork inherited this relationship. However code-bases are no longer related nor are mergable. 

Would you mind if I import my fork into my organization as a fresh new repository to clear the fork relationship ? I'd obviously be glad to add proper credits for your work and link to your archived repository.

**Comment by edtan** [comment]
You're right, the fork relationship doesn't really make sense.  Sure, feel free to create a fresh new repository and I'll archive this repo.  Thanks!

**Comment by psycofdj** [comment]
Here you go:
* https://github.com/orange-cloudfoundry/gitlab-release-resource
* https://github.com/orange-cloudfoundry/gitlab-release-resource/releases/tag/v1.0.2

**Comment by edtan** [comment]
I've now updated the README and repo description, and will archive this repo shortly.  Thanks for your work, and continuing on the GitLab release resource!

**Pull request closed without merging**
